StarWars/Models/ErrorViewModel.cs
namespace StarWars.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

StarWars/Controllers/FilmsController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using StarWars.Domain.Models;
using StarWars.Service.Queries;
using Film = StarWars.Data.Entities.Film;

namespace StarWars.Controllers;

public class FilmsController : Controller
{
    private readonly IMediator _mediator;
    private readonly IMapper _mapper;

    public FilmsController(IMediator mediator, IMapper mapper)
    {
        _mapper = mapper;
        _mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var films = _mapper.Map<List<Film>, List<FilmViewModel>>(
            await _mediator.Send(new GetFilmsQuery
            {
                Populate = null,
                OrderBy = null,
                SearchExp = null,
                CacheKey = $"{Request.Path}{Request.QueryString}"
            })
        );
        return films.Any() ? View(films) : Problem("An error occurred getting the films.");
    }
}

StarWars/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using StarWars.Models;

namespace StarWars.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

StarWars/Controllers/PeopleController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using StarWars.Service.Queries;
using StarWars.Service.Services.Interfaces;

namespace StarWars.Controllers;

public class PeopleController : Controller
{
    private readonly IMediator _mediator;

    public PeopleController(IMediator mediator)
    {
        _mediator = mediator;
    }

    // GET
    public async Task<IActionResult> Index()
    {
        var people = await _mediator.Send(new GetPeopleQuery
        {
            Populate = null,
            OrderBy = null,
            SearchExp = null,
            CacheKey = $"{Request.Path}{Request.QueryString}"
        });
        return people.Any() ? View(people) : Problem("An error occurred getting the people.");
    }
}

StarWars/Views/Films/Index.cshtml
@model IEnumerable<StarWars.Domain.Models.FilmViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Films</h1>

@* <p> *@
@*     <a asp-action="Create">Create New</a> *@
@* </p> *@
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Director)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Producer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Characters)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Producer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Characters)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | *@
                @* <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
                @* <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
            </td>
        </tr>
    }
    </tbody>
</table>

StarWars/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Star Wars";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h3>“may the force be with you”</h3>
</div>

StarWars/Views/People/Create.cshtml
@model StarWars.Data.Entities.People

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>People</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        @* <form asp-action="Create"> *@
        @*     <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
        @*     <div class="form-group"> *@
        @*         <label asp-for="Name" class="control-label"></label> *@
        @*         <input asp-for="Name" class="form-control" /> *@
        @*         <span asp-validation-for="Name" class="text-danger"></span> *@
        @*     </div> *@
        @*     <div class="form-group"> *@
        @*         <input type="submit" value="Create" class="btn btn-primary" /> *@
        @*     </div> *@
        @* </form> *@
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

StarWars/Views/People/Delete.cshtml
@model StarWars.Data.Entities.People

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>People</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    @* <form asp-action="Delete"> *@
    @*     <input type="hidden" asp-for="Id" /> *@
    @*     <input type="submit" value="Delete" class="btn btn-danger" /> | *@
    @*     <a asp-action="Index">Back to List</a> *@
    @* </form> *@
</div>

StarWars/Views/People/Details.cshtml
@model StarWars.Data.Entities.People

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>People</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    @* <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> | *@
    <a asp-action="Index">Back to List</a>
</div>

StarWars/Views/People/Edit.cshtml
@model StarWars.Data.Entities.People

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>People</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        @* <form asp-action="Edit"> *@
        @*     <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
        @*     <input type="hidden" asp-for="Id" /> *@
        @*     <div class="form-group"> *@
        @*         <label asp-for="Name" class="control-label"></label> *@
        @*         <input asp-for="Name" class="form-control" /> *@
        @*         <span asp-validation-for="Name" class="text-danger"></span> *@
        @*     </div> *@
        @*     <div class="form-group"> *@
        @*         <input type="submit" value="Save" class="btn btn-primary" /> *@
        @*     </div> *@
        @* </form> *@
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

StarWars/Views/People/Index.cshtml
@model IEnumerable<StarWars.Data.Entities.People>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>People</h1>

@* <p> *@
@*     <a asp-action="Create">Create New</a> *@
@* </p> *@
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EyeColor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HairColor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SkinColor)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EyeColor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HairColor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SkinColor)
            </td>
            <td>
                @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | *@
                @* <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
                @* <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
            </td>
        </tr>
    }
    </tbody>
</table>

StarWars/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - StarWars</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/StarWars.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Star Wars</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Films" asp-action="Index">Films</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="/api/doc" target="_blank">API Doc</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Star Wars - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>